spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/it_asset_management}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:@Vedu#007}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}